name: 'golangci-lint'
on:
  pull_request:
  push:
    branches:
      - 'master'

permissions:
  contents: 'read'

jobs:
  golangci:
    name: 'lint'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/setup-go@v5'
        with:
          cache: false
          go-version: '^1.22'
      - uses: 'actions/checkout@v4'
      - uses: 'golangci/golangci-lint-action@v6'
        with:
          only-new-issues: true
