name: test
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '^1.22'
      - uses: actions/checkout@v4
      - uses: n8maninger/action-golang-test@v2
